### ISSUE TITLE
Compile with nginx 1.2.8 version

### ISSUE THREAD

**Issue by MikeVL** [mdirolf/nginx-gridfs#51]
```
gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  --std=c99 -Isrc  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail \
        -o objs/addon/src/mongo.o \
        /root/nginx-gridfs/mongo-c-driver/src/mongo.c
/root/nginx-gridfs/mongo-c-driver/src/mongo.c: In function ‘mongo_count’:
/root/nginx-gridfs/mongo-c-driver/src/mongo.c:939:5: error: missing initializer [-Werror=missing-field-initializers]
/root/nginx-gridfs/mongo-c-driver/src/mongo.c:939:5: error: (near initialization for ‘out.dataSize’) [-Werror=missing-field-initializers]
/root/nginx-gridfs/mongo-c-driver/src/mongo.c: In function ‘mongo_simple_int_command’:
/root/nginx-gridfs/mongo-c-driver/src/mongo.c:981:5: error: missing initializer [-Werror=missing-field-initializers]
/root/nginx-gridfs/mongo-c-driver/src/mongo.c:981:5: error: (near initialization for ‘out.dataSize’) [-Werror=missing-field-initializers]
/root/nginx-gridfs/mongo-c-driver/src/mongo.c: In function ‘mongo_simple_str_command’:
/root/nginx-gridfs/mongo-c-driver/src/mongo.c:1013:5: error: missing initializer [-Werror=missing-field-initializers]
/root/nginx-gridfs/mongo-c-driver/src/mongo.c:1013:5: error: (near initialization for ‘out.dataSize’) [-Werror=missing-field-initializers]
/root/nginx-gridfs/mongo-c-driver/src/mongo.c: In function ‘mongo_cmd_get_error_helper’:
/root/nginx-gridfs/mongo-c-driver/src/mongo.c:1055:5: error: missing initializer [-Werror=missing-field-initializers]
/root/nginx-gridfs/mongo-c-driver/src/mongo.c:1055:5: error: (near initialization for ‘out.dataSize’) [-Werror=missing-field-initializers]
/root/nginx-gridfs/mongo-c-driver/src/mongo.c: In function ‘mongo_cmd_ismaster’:
/root/nginx-gridfs/mongo-c-driver/src/mongo.c:1098:5: error: missing initializer [-Werror=missing-field-initializers]
/root/nginx-gridfs/mongo-c-driver/src/mongo.c:1098:5: error: (near initialization for ‘out.dataSize’) [-Werror=missing-field-initializers]
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/mongo.o] Error 1
```
