### ISSUE TITLE
Cannot compile with geoip module

### ISSUE THREAD

**Issue by ualtinok** [mdirolf/nginx-gridfs#41]
When configured nginx like this:

./configure --add-module=../nginx-gridfs/  --with-http_geoip_module

compiling nginx ends with an error:

```
            -o objs/src/http/modules/ngx_http_split_clients_module.o \
            src/http/modules/ngx_http_split_clients_module.c
```

src/http/modules/ngx_http_geoip_module.c:173: error: 'GeoIPRecord' has no member named 'dma_code'
make[1]: **\* [objs/src/http/modules/ngx_http_geoip_module.o] Error 1
make[1]: **\* Waiting for unfinished jobs....
make[1]: Leaving directory `/home/setups/nginx-1.0.11'

without nginx-gridfs or without geoip module it compiles successfully. (NGINX VERSION: nginx-1.0.11)

**Comment by bodomic** [comment]
I can reproduce this issue too, trying to build on Debian 6.0.3 x86_64

**Comment by iamjstates** [comment]
I don't have the same error as above but it could be related.  I'm using OS X 10.7 and trying to install nginx-1.3.0. When I try to install nginx-gridfs it fails at:

src/http/modules/ngx_http_geoip_module.c:197: error: ‘GeoIPRecord’ has no member named ‘dma_code’
gmake[1]: **\* [objs/src/http/modules/ngx_http_geoip_module.o] Error 1

Once I remove the --add-module=/path/to/nginx-gridfs it compiles fine.

**Comment by amartinj** [comment]
Same happened for me with nginx-1.2.4. I disabled geoip module and it worked. Seems that both geoip module and gridfs cannot be enabled.

**Comment by bwellsnc** [comment]
This can be compiled together.  Please reference this page:
https://github.com/borisz/geoip-api-c

You will need to add -fms-extensions to your CFLAGS.  This built geoip and gridfs together

**Comment by amartinj** [comment]
Thanks for the answer :+1:
